sudo: required
language: python3.6
services:
  - docker
env:
  global:
    - S3_BUCKET=nthienan-public
    - S3_PREFIX=cloudformation/aws-elb
install: true

before_deploy:
  - pip install --user awscli
deploy:
  - provider: script
    script: aws s3 cp classic-elb.yaml s3://$S3_BUCKET/$S3_PREFIX
    on:
      branch: master